version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
stack_name = "line-app"
resolve_s3 = true
s3_prefix = "line-app"
confirm_changeset = true
disable_rollback = true
image_repositories = []

