version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\" ChannelType=\"LIFF\""
stack_name = "demo-line-app"
resolve_s3 = true
s3_prefix = "demo-line-app"
confirm_changeset = true
disable_rollback = true
image_repositories = []
